/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alfanumerico.Numeros.variables;

/**
 *
 * @author Windows 11
 */
public class menu_variable extends javax.swing.JFrame {

    /**
     * Creates new form menu_variable
     */
    public menu_variable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido al menu de letras con variables");

        jLabel2.setText("Por favor seleccione una opcion:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejercicio No. 1: lea dos números enteros  y los muestre por pantalla.", "Ejercicio No. 3:lee un número entero y  muestra el doble y el triple de ese número.", "Ejercicio No. 4:lea una cantidad de grados centígrados y la pase a grados Fahrenheit", "Ejercicio No. 5: lee  el valor del radio de una circunferencia, calcula y muestra la longitud y el área de la circunferencia.", "Ejercicio No. 6:pasa una velocidad en Km/h a m/s.", "Ejercicio No. 7:longitud de los catetos de un triángulo rectángulo y calcular la longitud dela hipotenusa según el teorema de Pitágoras.", "Ejercicio No. 8:la longitud del radio una esfera , calcular y escribe el volumen de la esfera que se corresponden con dicho radio.", "Ejercicio No. 9:calcular el área de un triángulo en función de las longitudes de sus lados (a, b, c)", "Ejercicio No. 10:leer un número entero de 3 cifras y muestre por separado las cifras del número.", "Ejercicio No. 11:lea un número entero N de 5 cifras y muestre sus cifras", "Ejercicio No. 12:lea un número entero N de 5 cifras y muestre sus cifras al reves ", "Ejercicio No. 13:fecha de nacimiento y calcule su número de la suerte." }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       int opcion = 0;
        
        opcion = jComboBox1.getSelectedIndex();
        if(opcion == 0){ //ir al menu de letras
           Ejercicio1 ejercicio=new Ejercicio1();
        }
        else if(opcion==1){// ir al menu de numeros
         Ejercicio3 ejercicio = new Ejercicio3();
        }else if(opcion==2){
            Ejercicio4 ejercicio =new Ejercicio4();
        }else if(opcion==3){
            Ejercicio5 ejercicio =new Ejercicio5();
        }else if(opcion==4){
            Ejercicio6 ejercicio = new Ejercicio6();
        }else if (opcion==5){
            Ejercicio7 ejercicio = new Ejercicio7();
        }else if (opcion==6){
            Ejercicio8 ejercicio = new Ejercicio8();
        }else  if(opcion==7){
            Ejercicio9 ejercicio =new Ejercicio9();
        }else if (opcion==8){
            Ejercicio10 ejercicio =new Ejercicio10();
        }else if(opcion==9){
             Ejercicio11 ejercicio =new Ejercicio11();
        }else if(opcion==10){
            Ejercicio12 ejercicio =new Ejercicio12();
        }else if(opcion==11){
             Ejercicio13 ejercicio =new Ejercicio13();
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_variable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_variable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_variable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_variable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_variable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
